In [1]:
import pandas as pd
import numpy as np

In [2]:
covid_data = pd.read_csv("COVID_county_data.csv")
census_data = pd.read_csv("acs2017_census_tract_data.csv")

In [3]:
covid_data.head()

         date     county       state     fips  cases  deaths
0  2020-01-21  Snohomish  Washington  53061.0      1     0.0
1  2020-01-22  Snohomish  Washington  53061.0      1     0.0
2  2020-01-23  Snohomish  Washington  53061.0      1     0.0
3  2020-01-24       Cook    Illinois  17031.0      1     0.0
4  2020-01-24  Snohomish  Washington  53061.0      1     0.0

In [4]:
census_data.head()

,TractId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001020100,Alabama,Autauga County,1845,899,946,2.4,86.3,5.2,0.0,...,0.5,0.0,2.1,24.5,881,74.2,21.2,4.5,0.0,4.6
1,1001020200,Alabama,Autauga County,2172,1167,1005,1.1,41.6,54.5,0.0,...,0.0,0.5,0.0,22.2,852,75.9,15.0,9.0,0.0,3.4
2,1001020300,Alabama,Autauga County,3385,1533,1852,8.0,61.4,26.5,0.6,...,1.0,0.8,1.5,23.1,1482,73.3,21.1,4.8,0.7,4.7
3,1001020400,Alabama,Autauga County,4267,2001,2266,9.6,80.3,7.1,0.5,...,1.5,2.9,2.1,25.9,1849,75.8,19.7,4.5,0.0,6.1
4,1001020500,Alabama,Autauga County,9965,5054,4911,0.9,77.5,16.4,0.0,...,0.8,0.3,0.7,21.0,4787,71.4,24.1,4.5,0.0,2.3

In [5]:
census_data.loc[census_data['County'] == 'Autauga County']

,TractId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001020100,Alabama,Autauga County,1845,899,946,2.4,86.3,5.2,0.0,...,0.5,0.0,2.1,24.5,881,74.2,21.2,4.5,0.0,4.6
1,1001020200,Alabama,Autauga County,2172,1167,1005,1.1,41.6,54.5,0.0,...,0.0,0.5,0.0,22.2,852,75.9,15.0,9.0,0.0,3.4
2,1001020300,Alabama,Autauga County,3385,1533,1852,8.0,61.4,26.5,0.6,...,1.0,0.8,1.5,23.1,1482,73.3,21.1,4.8,0.7,4.7
3,1001020400,Alabama,Autauga County,4267,2001,2266,9.6,80.3,7.1,0.5,...,1.5,2.9,2.1,25.9,1849,75.8,19.7,4.5,0.0,6.1
4,1001020500,Alabama,Autauga County,9965,5054,4911,0.9,77.5,16.4,0.0,...,0.8,0.3,0.7,21.0,4787,71.4,24.1,4.5,0.0,2.3
5,1001020600,Alabama,Autauga County,3620,1765,1855,3.0,70.7,25.1,0.0,...,0.7,3.5,8.0,21.1,1364,84.0,14.1,1.9,0.0,6.1
6,1001020700,Alabama,Autauga County,3420,1459,1961,4.0,78.0,13.7,0.6,...,0.0,0.0,0.0,16.4,1418,77.4,17.6,5.0,0.0,16.9
7,1001020801,Alabama,Autauga County,2913,1495,1418,4.2,86.3,7.1,1.5,...,0.0,0.7,5.2,24.6,1369,72.7,17.5,8.8,1.0,7.2
8,1001020802,Alabama,Autauga County,11333,5488,5845,1.4,81.8,15.3,0.0,...,0.0,0.0,2.2,27.4,4857,70.1,22.5,7.4,0.0,2.2
9,1001020900,Alabama,Autauga County,6167,3111,3056,1.0,86.2,9.7,0.8,...,0.0,5.0,5.9,35.6,2781,80.4,14.5,5.0,0.0,6.8
10,1001021000,Alabama,Autauga County,2796,1440,1356,0.8,71.5,25.7,0.8,...,3.5,0.4,1.1,35.6,1202,75.4,19.0,5.7,0.0,6.0
11,1001021100,Alabama,Autauga County,3153,1487,1666,0.7,46.3,53.0,0.0,...,0.4,3.2,2.1,31.8,1270,69.4,24.7,5.8,0.0,5.4

In [6]:
unique_counties = census_data['County'].drop_duplicates()

In [7]:
unique_counties

0             Autauga County
12            Baldwin County
44            Barbour County
53               Bibb County
57             Blount County
                ...
73958    Vega Baja Municipio
73972      Vieques Municipio
73975     Villalba Municipio
73981      Yabucoa Municipio
73990        Yauco Municipio
Name: County, Length: 1955, dtype: object

In [8]:
census_data = census_data.drop(columns=["TractId"])

In [9]:
census_percentages = []

In [10]:
new_census = census_data.copy()

In [11]:
census_data.head()

,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,Alabama,Autauga County,1845,899,946,2.4,86.3,5.2,0.0,1.2,...,0.5,0.0,2.1,24.5,881,74.2,21.2,4.5,0.0,4.6
1,Alabama,Autauga County,2172,1167,1005,1.1,41.6,54.5,0.0,1.0,...,0.0,0.5,0.0,22.2,852,75.9,15.0,9.0,0.0,3.4
2,Alabama,Autauga County,3385,1533,1852,8.0,61.4,26.5,0.6,0.7,...,1.0,0.8,1.5,23.1,1482,73.3,21.1,4.8,0.7,4.7
3,Alabama,Autauga County,4267,2001,2266,9.6,80.3,7.1,0.5,0.2,...,1.5,2.9,2.1,25.9,1849,75.8,19.7,4.5,0.0,6.1
4,Alabama,Autauga County,9965,5054,4911,0.9,77.5,16.4,0.0,3.1,...,0.8,0.3,0.7,21.0,4787,71.4,24.1,4.5,0.0,2.3

In [12]:
#new_census.columns = census_data.columns

In [13]:
new_census.drop(new_census.index, inplace=True)

In [14]:
new_census

Empty DataFrame
Columns: [State, County, TotalPop, Men, Women, Hispanic, White, Black, Native, Asian, Pacific, VotingAgeCitizen, Income, IncomeErr, IncomePerCap, IncomePerCapErr, Poverty, ChildPoverty, Professional, Service, Office, Construction, Production, Drive, Carpool, Transit, Walk, OtherTransp, WorkAtHome, MeanCommute, Employed, PrivateWork, PublicWork, SelfEmployed, FamilyWork, Unemployment]
Index: []

[0 rows x 36 columns]

In [ ]:
new_row = np.empty((1,36))
for x in unique_counties:
    group = census_data.loc[census_data['County'] == x]
    for i in census_data.columns:
        if i == 'County' or i == 'State':
            new_row = np.append(new_row, x)
        if census_data[i].dtypes == 'int64':
            new_row = np.append(new_row, sum(group[i]))
        if census_data[i].dtypes == 'float64':
            new_row = np.append(new_row, (sum(group[i])/group[i].size)*100)
    temp = pd.DataFrame(new_row)
    new_census.append(temp)
    new_row = np.empty((1,36))

In [ ]:
new_census

In [35]:
temp2 = pd.DataFrame(new_row,columns=new_census.columns)

ValueError: Shape of passed values is (70380, 1), indices imply (70380, 36)

In [32]:
temp2

Empty DataFrame
Columns: [State, County, TotalPop, Men, Women, Hispanic, White, Black, Native, Asian, Pacific, VotingAgeCitizen, Income, IncomeErr, IncomePerCap, IncomePerCapErr, Poverty, ChildPoverty, Professional, Service, Office, Construction, Production, Drive, Carpool, Transit, Walk, OtherTransp, WorkAtHome, MeanCommute, Employed, PrivateWork, PublicWork, SelfEmployed, FamilyWork, Unemployment]
Index: []

[0 rows x 36 columns]

In [33]:
new_row

[]

Index(['State', 'County', 'TotalPop', 'Men', 'Women', 'Hispanic', 'White',
       'Black', 'Native', 'Asian', 'Pacific', 'VotingAgeCitizen', 'Income',
       'IncomeErr', 'IncomePerCap', 'IncomePerCapErr', 'Poverty',
       'ChildPoverty', 'Professional', 'Service', 'Office', 'Construction',
       'Production', 'Drive', 'Carpool', 'Transit', 'Walk', 'OtherTransp',
       'WorkAtHome', 'MeanCommute', 'Employed', 'PrivateWork', 'PublicWork',
       'SelfEmployed', 'FamilyWork', 'Unemployment'],
      dtype='object')

Index(['State', 'County', 'TotalPop', 'Men', 'Women', 'Hispanic', 'White',
       'Black', 'Native', 'Asian', 'Pacific', 'VotingAgeCitizen', 'Income',
       'IncomeErr', 'IncomePerCap', 'IncomePerCapErr', 'Poverty',
       'ChildPoverty', 'Professional', 'Service', 'Office', 'Construction',
       'Production', 'Drive', 'Carpool', 'Transit', 'Walk', 'OtherTransp',
       'WorkAtHome', 'MeanCommute', 'Employed', 'PrivateWork', 'PublicWork',
       'SelfEmployed', 'FamilyWork', 'Unemployment'],
      dtype='object')

In [26]:
new_census.columns

Index(['State', 'County', 'TotalPop', 'Men', 'Women', 'Hispanic', 'White',
       'Black', 'Native', 'Asian', 'Pacific', 'VotingAgeCitizen', 'Income',
       'IncomeErr', 'IncomePerCap', 'IncomePerCapErr', 'Poverty',
       'ChildPoverty', 'Professional', 'Service', 'Office', 'Construction',
       'Production', 'Drive', 'Carpool', 'Transit', 'Walk', 'OtherTransp',
       'WorkAtHome', 'MeanCommute', 'Employed', 'PrivateWork', 'PublicWork',
       'SelfEmployed', 'FamilyWork', 'Unemployment'],
      dtype='object')